### ISSUE TITLE
Does anyone encounter problem with the tagging tool?

### ISSUE THREAD

**Issue by wangcongcong123** [viczong/extract_COVID19_events_from_Twitter#13]
I tried [this tagging tool](https://github.com/aritter/twitter_nlp) as specified in this repository.  After testing it on Mac, Windows, and Linux,  the following issue still raises.

"module html.parser not found"

I searched solutions to this issue online, none can properly help fix this issue.

does anyone encounter the same issue?

A following-up question related to this is that why the tagging process is needed now that the char-chunks offsets are already in the datatset?

**Comment by akhilavh** [comment]
Yes. I too have faced this issue. Couldn't get any lead for solving this
issue from online.

**Comment by s4zong** [comment]
Oh really? I have been using it for a very long time. I will take a look at this.

**Comment by s4zong** [comment]
> A following-up question related to this is that why the tagging process is needed now that the char-chunks offsets are already in the datatset?

The input of the model should be the tokenized text.

**Comment by s4zong** [comment]
@wangcongcong123 Can you provide more information for this issue (e.g., screenshot for this matter, py version, linux environment, etc.)? It looks all good at my side.

**Comment by wangcongcong123** [comment]
Below is the full error message. I use python 2.7

Traceback (most recent call last):
  File "python/ner/extractEntities2_json.py", line 26, in <module>
    import twokenize
  File "/home/congcong/venv27/lib/python2.7/site-packages/twokenize/__init__.py", line 1, in <module>
    from .twokenize import *
  File "/home/congcong/venv27/lib/python2.7/site-packages/twokenize/twokenize.py", line 27, in <module>
    import html.parser as HTMLParser
ImportError: No module named html.parser

My Linux environment is:
Linux xxx 5.4.0-42-generic #46~18.04.1-Ubuntu SMP Fri Jul 10 07:21:24 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by s4zong** [comment]
So it seems it is to the version issue of "twokenize". Actually there is a twokenize.py in tagging's repo. Maybe you could try to use that instead of the pre-installed version. And the tagging tool seems not using "html.parser".

**Comment by Supermaxman** [comment]
I solved this my making sure I ran the bash build.sh in the tagging repo and not pip installing twokenize separately, as it is some other package built for python 3. Make sure twokenize is using the tagging repo's tokenizing code and not some other pip package.

**Comment by akhilavh** [comment]
Can you please explain..  I had run the bash in tagging repo. How to add
the ner to our working code.
