### ISSUE TITLE
Annotation Platform

### ISSUE THREAD

**Issue by Gautamshahi** [viczong/extract_COVID19_events_from_Twitter#15]
Hi,

In the paper, in section 2.1 and Appendix B, you mentioned about the annotation platform. Which annotation platform did you use? Is it public?

**Comment by s4zong** [comment]
Hello,

We use Amazon Mechanical Turk platform, as mentioned in Section 2.1.

**Comment by Gautamshahi** [comment]
Hi, Thanks, what about the UI, is it open source?

**Comment by s4zong** [comment]
Mechanical Turk has some in-built templates. It also supports building the interface by javascript (.html). We just write our own.

**Comment by Gautamshahi** [comment]
oh, thanks
