### ISSUE TITLE
Cleaned data request for baseline

### ISSUE THREAD

**Issue by JackqqWang** [viczong/extract_COVID19_events_from_Twitter#2]
Dear Community,

     We are happy to join this challenge.

     Our team is working on the models. However, if we could run the baseline, that would be a great help. May we ask we could get access to the cleaned data for each team to get the same result running the baseline?

     Thank you.

Best,
Jack

**Comment by s4zong** [comment]
Hi,

Just wanted to make sure - what you mean by "cleaned data"? Maybe you need a data pre-processing script?

Thanks,

**Comment by JackqqWang** [comment]
Hi,

   Thanks for your reply.

    That would be great if a data pre-processing script is available.

    Thanks.

Best,
Jiaqi

**Comment by s4zong** [comment]
OK we will provide one this week.

Thanks,

**Comment by JackqqWang** [comment]
Thanks!
