### ISSUE TITLE
Would part 1 result be finally evaluated?

### ISSUE THREAD

**Issue by YangAzure** [viczong/extract_COVID19_events_from_Twitter#4]
Currently only the part 2 prediction results are required to be submitted. Would the result of part 1 be also evaluated in this shared task? If not, would it be possible to directly build the part 2 model for this task?

**Comment by s4zong** [comment]
Hi,

I think our current plan is to evaluate the output for part2.

Thanks,

**Comment by YangAzure** [comment]
Got it. Thanks for the information.
