### ISSUE TITLE
data preparation - error

### ISSUE THREAD

**Issue by akhilavh** [viczong/extract_COVID19_events_from_Twitter#5]
Hello,
We are delighted to work towards this event. During data preparation, we happened to see the following:

===============================================================================
INFO:root:Reading annotations from /home/extract_COVID19_events_from_Twitter-master/data/positive.jsonl file...
INFO:root:Total annotations:2500
INFO:root:Creating labeled data instances from annotations...
Traceback (most recent call last):
  File "/home/extract_COVID19_events_from_Twitter-master/model/data_preprocessing.py", line 341, in <module>
    main()
  File "/home/extract_COVID19_events_from_Twitter-master/model/data_preprocessing.py", line 335, in main
    task_instances_dict, tag_statistics, question_keys_and_tags = make_instances_from_dataset(dataset)
  File "/home/extract_COVID19_events_from_Twitter-master/model/data_preprocessing.py", line 151, in make_instances_from_dataset
    dummy_annotation = dataset[0]['consensus_annotation']
KeyError: 'consensus_annotation'

===============================================================================

Please help me figure out where we have to make corrections while working with this project.

Thank you for your time.
Good Day!

Regards,
Akhila

**Comment by s4zong** [comment]
Hi,

Thanks for raising this issue. We have been working on updating the repo this week. Please follow our updated instructions for running the baseline.

Thanks,

**Comment by akhilavh** [comment]
> Hi,
> 
> Thanks for raising this issue. We have been working on updating the repo this week. Please follow our updated instructions for running the baseline.
> 
> Thanks,

Thank you for your response.
