### ISSUE TITLE
In your result, you have some metrics available for evaluation. What in detail should be used for the final score calculation in the testset?

### ISSUE THREAD

**Issue by YangAzure** [viczong/extract_COVID19_events_from_Twitter#8]

**Comment by s4zong** [comment]
Hello,

We specify the system output and also an evaluation script to use in https://github.com/viczong/extract_COVID19_events_from_Twitter/tree/master/shared_task.

Thanks,

**Comment by YangAzure** [comment]
Thanks for the prompt reply! We'll try it out.
