### ISSUE TITLE
Evaluation 

### ISSUE THREAD

**Issue by JackqqWang** [viczong/extract_COVID19_events_from_Twitter#9]
Dear Community,

Can I ask we should evaluate our results in terms of F1, P, and R or some other scores in the results?

Thank you.

Best,

Jack

**Comment by s4zong** [comment]
Hello,

Please use the script here to evaluate https://github.com/viczong/extract_COVID19_events_from_Twitter/tree/master/shared_task. We will use F1 score.

Thanks,
